[deps]
MiniLoggers = "93f3dd0f-005d-4452-894a-a31841fa4078"
REPLSmuggler = "ad7bff83-59f0-4382-9fe5-c2ac8aa77434"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SixelTerm = "65edfddc-f399-4499-8369-a1bd38eee2ea"
